

# 1. motivation

都道府県の地図にポイントでプロットしたいと思ったが、
いい感じのデータがない。

国土地理院が各都道府県の"都道府県庁", "東端", "西端", "南端", "北端"の位置情報を掲載しているが、
何故かPDFなのとDMM形式？だがDMS形式？も欲しかったりする。


[日本の東西南北端点の経度緯度](https://www.gsi.go.jp/KOKUJYOHO/center.htm)
[都道府県の庁舎及び東西南北端点の経緯度(世界測地系）](https://www.gsi.go.jp/KOKUJYOHO/CENTER/kendata/zenken.pdf)


```{r}
library(sp)
library(tidyverse)
library(readxl)
library(pdftools)
```


```{r}
data_pdf <- pdf_text("https://www.gsi.go.jp/KOKUJYOHO/CENTER/kendata/zenken.pdf")

data_bind_pdf <- NULL

for(page in data_pdf) {
  data_bind_pdf <- paste0(data_bind_pdf, page)
}

data_bind_pdf_split <- 
  data_bind_pdf %>% 
  str_replace_all(pattern = patterns_remove, replacement = " ") %>%
  str_replace_all(pattern = "\n経度", replacement = " 経度") %>%
  str_replace_all(pattern = "\n緯度", replacement = " 緯度") %>% 
  str_replace_all(pattern = "″\n", replacement = "″″\n") %>%
  str_replace_all(pattern = "\"", replacement = "″") %>%
  str_replace_all(pattern = "         東端         西端         南端         北端 ", replacement = " ") %>%
  str_remove(pattern = "^.*該当場所の地図が表示されます。\n") %>% 
  str_remove_all(pattern = " .*庁") %>% 
  # str_replace_all(pattern = "″″", replacement = "″") %>%
  trimws() %>% 
  str_split(pattern = "″\n") %>% 
  .[[1]] %>% map_chr(., ~ str_replace_all(., pattern = "″″", replacement = "″"))
```


```{r}
char_to_dms <- function(kokudo_todofuken) {
  name_todofuken <- kokudo_todofuken %>% str_extract(., pattern="...??[都道府県]")
  ido_start <- kokudo_todofuken %>% str_locate("緯度") %>% .[2]
  ido_end <- kokudo_todofuken %>% nchar()
  ido <- 
    kokudo_todofuken %>% str_sub(ido_start + 2, ido_end) %>% 
    str_split(pattern = "″ ") %>% 
    .[[1]] %>% 
    .[1:5] %>% 
     paste0(., "″W")
  
  keido_start <- kokudo_todofuken %>% str_locate("経度") %>% .[2]
  keido_end <- kokudo_todofuken %>% str_locate("緯度") %>% .[2]
  keido <- 
    kokudo_todofuken %>% str_sub(keido_start + 2, keido_end -3) %>% 
    str_split(pattern = "″ ") %>% 
    .[[1]] %>% 
    .[1:5] %>% 
     paste0(., "″W") 
  
  chd = "°"
  chm = "′"
  chs = "″"
  
  ido_dms <- char2dms(ido, chd = chd,chm = chm,chs = chs) %>% as.numeric()
  keido_dms <- char2dms(keido, chd = chd,chm = chm,chs = chs) %>% as.numeric()
  
  df_return <- 
    tibble(Todohuken = name_todofuken,
           Category = c("都道府県庁", "東端", "西端", "南端", "北端"),
           Latitude_dmm = ido,
           Longitude_dmm = keido,
           Latitude_dms = ido_dms*-1,
           Longitude_dms = keido_dms*-1)
  return(df_return)
}

```
DMM
```{r}
geo_todofuken <- map_dfr(.x = data_bind_pdf_split, .f = char_to_dms)
geo_todofuken %>% head(10)
# # A tibble: 10 x 6
#    Todohuken Category   Latitude_dmm Longitude_dmm Latitude_dms Longitude_dms
#    <chr>     <chr>      <chr>        <chr>                <dbl>         <dbl>
#  1 北海道    都道府県庁 43°03′51″W   141°20′49″W           43.1          141.
#  2 北海道    東端       45°30′22″W   148°53′35″W           45.5          149.
#  3 北海道    西端       41°31′02″W   139°20′04″W           41.5          139.
#  4 北海道    南端       41°21′07″W   139°47′57″W           41.4          140.
#  5 北海道    北端       45°33′26″″W  148°45′08″″W          45.6          149.
#  6 青森県    都道府県庁 40°49′28″W   140°44′24″W           40.8          141.
#  7 青森県    東端       40°27′07″W   141°41′00″W           40.5          142.
#  8 青森県    西端       40°32′03″W   139°29′49″W           40.5          139.
#  9 青森県    南端       40°13′04″W   141°00′46″W           40.2          141.
# 10 青森県    北端       41°33′22″″W  140°54′42″″W          41.6          141.
```

```{r}
library(leaflet)

leaflet_map <- 
  leaflet(geo_todofuken %>% filter(Category == "都道府県庁")) %>% 
  setView(lat = 35.68228805092929, lng = 139.76997811851874, zoom = 7.5) %>% 
  # addAwesomeMarkers(~139.77447, ~35.687740, icon=icons, label=~as.character("HQ")) %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% 
  addMarkers(~Longitude_dms, ~Latitude_dms,
             popup = ~as.character(Category), label = ~as.character(Todohuken)) 
leaflet_map
```






